### ISSUE TITLE
Does not sems to work at all

### ISSUE THREAD

**Issue by mikeSimonson** [psecio/versionscan#10]
I am just trying to run the scanner after installing it globally with composer.
I can only get that result
```sh
$ versionscan scan
   ERROR:                    
   [0] Invalid check configuration
```
or
```sh
$ versionscan scan --version 5.4
PHP Version Security Scanner version 0.1
```
or
```sh
$ versionscan scan --version 5.4.22
PHP Version Security Scanner version 0.1
```
or
```sh
$ versionscan scan --version 5.5
PHP Version Security Scanner version 0.1
```
or
```sh
$ versionscan scan --version 5.6
PHP Version Security Scanner version 0.1
```

What am I doing wrong ?

**Comment by majkel89** [comment]
This issue is probably addressed by https://github.com/psecio/versionscan/pull/8 (it is not yet merged).
Try to checkout https://github.com/marcelsud/versionscan

**Comment by enygma** [comment]
sorry about that...the PR that corrected it was merged late yesterday.

**Comment by jkrehm** [comment]
When are you planning a new version tag? Perhaps a 1.4.1? That way we get the fixed JSON without having to resort to dev-master.

**Comment by enygma** [comment]
Done! My apologies - I thought I had tagged it after that. There's a 1.4.1 now.

**Comment by jkrehm** [comment]
Thank you!
