### ISSUE TITLE
Irrevelant output for Packaged PHP.

### ISSUE THREAD

**Issue by remicollet** [psecio/versionscan#12]
Most linux distribution provide packaged PHP versions, with security backport, ex: http://www.redhat.com/advice/speaks_backport.html

Providing such a tool just introduce more confusion.

The "isVulnerable()" test should not rely only on the version number but rather on a reproducer result (but, yes, I imagine this is a huge work).

Proposal: add a simple disclaimer

    if (is_executable('/bin/rpm')) {
    	@exec("/bin/rpm -qf ".PHP_BINARY, $ret, $error);
    	if (!$error) {
    		echo "DISCLAIMER: you are using a packaged PHP version (".$ret[0].")\nCheck with your provider for security backport\n";
    	}
    }

This one is for RPM based distro, same could be written for DEB or other package format.

**Comment by enygma** [comment]
Yup, this is a known issue - there's already some discussion about it over in issue #5. There's plans to get this kind of thing into the tool, but it's still pending as of now.

**Comment by remicollet** [comment]
Yes, this is the reason why I propose this small disclaimer, just to avoid confusion.

**Comment by colinodell** [comment]
I'm going to close this so we can consolidate the discussion into #5.  Thanks!
