### ISSUE TITLE
Do you need help maintaining this project?

### ISSUE THREAD

**Issue by colinodell** [psecio/versionscan#22]
I'm seeing several issues and pull requests with "new" CVEs that haven't been merged in.  Can I help you review and merge these, ensuring this list stays up-to-date?

**Comment by enygma** [comment]
That would be excellent :) I'm afraid there's only so much time in the day....

**Comment by philsturgeon** [comment]
Do I sense another league project? We'd all be super happy to help keep things merged and whatnot. :)

--
Phil Sturgeon

**Comment by enygma** [comment]
More than happy to move it under that umbrella if it helps it become more maintained and a more useful resource :)

**Comment by colinodell** [comment]
Thanks @enygma!  I'm going to start by cleaning up the `checks.json` file (de-duping it, ordering everything by CVE ID, and enforcing this with automated tests).  From there I'll review the proposed changes to that file and manually merge them in.  That should hopefully get things (relatively) up-to-date.
