### ISSUE TITLE
[Feature] auto-updating of checks.json using the missing command

### ISSUE THREAD

**Issue by lightswitch05** [psecio/versionscan#32]
Using [travis-ci cron jobs](https://docs.travis-ci.com/user/cron-jobs/), it would be possible to have the `missing` command ran on a regular basis and any updates automatically committed to a separate branch. From there, a maintainer with the correct permissions could review the changes and merge them into master. Preferably, the cron job would be ran daily and no commits would be made if there were no new CVEs discovered.

I would be willing to implement this feature myself, given a few requirements:

* While I can set this all up in my own fork to get the development and testing complete, **someone with admin access to the project would be required to re-implement some of the travis-ci setup directly for this repo.** This is an absolute requirement of the feature and cannot be completed if there is no more interest in maintaining this project
* More people are needed with merge permissions on this repo. Automatic updates are great, but if no one is going to review and merge them - then there is no point.
* More people are needed with `packagist.org` permissions. This requirement is basically the same as above. Merging to master is fine, but legitimate package releases need to be created

If the above requirements are satisfied, and there is interest in this tool being maintained by the community, then I would be happy to implement this feature. Once automatic updates have been achieved, I believe #11 would be a natural next-phase for this project.

**Comment by enygma** [comment]
I like the idea of this - keeping the CVEs updated has definitely been one of the biggest pain points of this project (and as you've noticed I've had less time for that unfortunately).

I'd love to see how you'd implement this - would you mind putting it together on a fork so I can see it in action?

**Comment by lightswitch05** [comment]
Yes, I'd be happy to. I just didn't want to put in the leg work if there was no interest. While you are here, I'd like to bring attention to the [packagist version](https://packagist.org/packages/psecio/versionscan), which is still out of date since my last pull request: https://github.com/psecio/versionscan/pull/31

**Comment by lightswitch05** [comment]
I've implemented this feature in a separate project: https://github.com/lightswitch05/php-version-audit
